### ISSUE TITLE
Internal Auth failed.

### ISSUE THREAD

**Issue by carnager** [pdaddyo/soundbounce#217]
![image](https://cloud.githubusercontent.com/assets/3321178/6560857/8c17b2f6-c68d-11e4-82a5-3ce8f6189312.png)

Some users on linux are getting this. stdout says it logged in successfully. instantly after this message appears.

**Comment by pdaddyo** [comment]
Hmmm this is strange, is it happening every time?

**Comment by carnager** [comment]
yes. 2 users reported it by now...

**Comment by gabrielfreiberg** [comment]
I'm getting this constantly on 2 different different machines using OSX Yosemite

**Comment by gabrielfreiberg** [comment]
I was able to get in by not using caps in the username when trying to sign in on OSX.

**Comment by i7c** [comment]
Hi,

I'm on linux, soundbounce version 20150301-1
So when I write my username as it is (with some letters in caps) I get the error posted above. If I follow gabrielfreiberg's hint and type it all lower case, it does sign in but then asks me for twitter or facebook authentication. If I click on the twitter button it spits out the following on stderr:

[27327:0328/193125:INFO:gpu_info_collector_x11.cc(80)] NVCtrl extension does not exist.
ATTENTION: default value of option force_s3tc_enable overridden by environment.
[27327:0328/193148:INFO:CONSOLE(9)] "Viewport argument value "device-width;" for key "width" is invalid, and has been ignored. Note that ';' is not a separator in viewport values. The list should be comma-separated.", source: https://api.twitter.com/oauth/authorize?oauth_token=... (9)
[27327:0328/193148:INFO:CONSOLE(9)] "Viewport argument value "1.0;" for key "initial-scale" was truncated to its numeric prefix. Note that ';' is not a separator in viewport values. The list should be comma-separated.", source: https://api.twitter.com/oauth/authorize?oauth_token=... (9)
[27327:0328/193148:INFO:CONSOLE(9)] "Viewport argument value "1.0;" for key "maximum-scale" was truncated to its numeric prefix. Note that ';' is not a separator in viewport values. The list should be comma-separated.", source: https://api.twitter.com/oauth/authorize?oauth_token=... (9)

and the window turns all white.
I opened the link in stderr and in my browser I could click on "authorize", which lead to this output in the browser:

Error: Failed to find request token in session
   at Strategy.OAuthStrategy.authenticate (/home/ubuntu/soundbounce/server/node_modules/passport-twitter/node_modules/passport-oauth1/lib/strategy.js:142:54)
   at Strategy.authenticate (/home/ubuntu/soundbounce/server/node_modules/passport-twitter/lib/strategy.js:85:40)
   at attempt (/home/ubuntu/soundbounce/server/node_modules/passport/lib/middleware/authenticate.js:341:16)
   at authenticate (/home/ubuntu/soundbounce/server/node_modules/passport/lib/middleware/authenticate.js:342:7)
   at Layer.handle [as handle_request] (/home/ubuntu/soundbounce/server/node_modules/express/lib/router/layer.js:82:5)
   at next (/home/ubuntu/soundbounce/server/node_modules/express/lib/router/route.js:100:13)
   at Route.dispatch (/home/ubuntu/soundbounce/server/node_modules/express/lib/router/route.js:81:3)
   at Layer.handle [as handle_request] (/home/ubuntu/soundbounce/server/node_modules/express/lib/router/layer.js:82:5)
   at /home/ubuntu/soundbounce/server/node_modules/express/lib/router/index.js:235:24
   at Function.proto.process_params (/home/ubuntu/soundbounce/server/node_modules/express/lib/router/index.js:313:12)

Hope this may help you to identify the issue here.

**Comment by gabrielfreiberg** [comment]
@i7c we are on OSX, twitter authentication is also not working, although its just a blank screen, im not sure where to see logs at.  The facebook authentication seems to work though.

**Comment by pdaddyo** [comment]
Thanks for details here.  I plan to remove the twitter/fb requirement, since it's only used to grab the username and an avatar.  We'll just use a default avatar and the spotify username.  I'll update this issue once that's done (no ETA yet I'm afraid).  In the meantime, as mentioned above, facebook auth works on OSX / linux. Alternatively, authorise twitter on windows, then it will log in as expected on OSX / linux.
