### ISSUE TITLE
Facebook Token Error

### ISSUE THREAD

**Issue by elishacoad** [pdaddyo/soundbounce#292]
Getting this error when logging into soundbounce using my Facebook. I'm inexperienced with node and was unsure of where the problem lay, so hopefully the attached error logs will be of help.

```
FacebookTokenError: This IP can't make requests for that application.
   at Strategy.parseErrorResponse (/home/ubuntu/soundbounce/server/node_modules/passport-facebook/lib/strategy.js:198:12)
   at Strategy.OAuth2Strategy._createOAuthError (/home/ubuntu/soundbounce/server/node_modules/passport-facebook/node_modules/passport-oauth2/lib/strategy.js:345:16)
   at /home/ubuntu/soundbounce/server/node_modules/passport-facebook/node_modules/passport-oauth2/lib/strategy.js:171:43
   at /home/ubuntu/soundbounce/server/node_modules/passport-facebook/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:177:18
   at passBackControl (/home/ubuntu/soundbounce/server/node_modules/passport-facebook/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:124:9)
   at IncomingMessage.<anonymous> (/home/ubuntu/soundbounce/server/node_modules/passport-facebook/node_modules/passport-oauth2/node_modules/oauth/lib/oauth2.js:143:7)
   at IncomingMessage.EventEmitter.emit (events.js:117:20)
   at _stream_readable.js:920:16
   at process._tickCallback (node.js:415:13)
```

**Comment by pdaddyo** [comment]
Thanks for this, our server changed IP I'm updating it now.  FYI we're working on v2 over here: https://github.com/pdaddyo/soundbounce-v2/
